
services:
  extract:
    image: sprecometer/extract
    build: .
    ports:
      - "8280:8280"
  graphite:
    image: graphiteapp/graphite-statsd
    ports:
      - 80:80
      - 2003-2004:2003-2004
      - 2023-2024:2023-2024
      - 8125:8125/udp
      - 8126:8126

